### ISSUE TITLE
still didn't solve the problem about the pretrained_models

### ISSUE THREAD

**Issue by wsp11** [ipc-lab/NDIC#5]

**Comment by wsp11** [comment]
Sorry,I still didn't figure it out.I test the code,but I met a new problem as below
![image](https://user-images.githubusercontent.com/103179618/171335096-f275e0c9-57ac-4559-8ca0-c2f50c1feb6e.png)
![image](https://user-images.githubusercontent.com/103179618/171335578-80c2fdce-779f-485c-9776-d660b83df4dd.png)
![image](https://user-images.githubusercontent.com/103179618/171337166-06bbb721-d8a5-4de3-917a-fdf0544953b8.png)
![image](https://user-images.githubusercontent.com/103179618/171337304-174db92c-141a-47e8-9afa-1ddce0d5852f.png)

**Comment by garjania** [comment]
Here the weight you used is for the original balle2017 model without using the side information. If you want to use only the balle2017 model change `use_side_info` to `False`. If you want to use ours+balle2017 you need to select weights from `balle17+ours/KITTI` in the given google drive link.

**Comment by wsp11** [comment]
Thanks you,I successfully get the result.
